### ISSUE TITLE
Reset and power off functions in Console do not work.

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/sample-web-ui#2367]
When choosing the option below to reset or power off the endpoint, they do not work, the system does nothing. 

![image](https://github.com/user-attachments/assets/14a0f759-e79b-41aa-9934-86f498995ae7)

Note: The Target customer experienced the same issue. 

Power ops from the dropdown list under the 3 dots, works great.

**Comment by madhavilosetty-intel** [comment]
Power off and reset commands function normally under standard conditions. However, these commands will be rejected during active:
- SOL (Serial Over LAN) sessions
- Storage Redirection sessions
- KVM (Keyboard, Video, Mouse) sessions

This behavior is by design to prevent disruption of active management sessions. Please ensure all redirection sessions are properly closed before attempting power operations. [Intel AMT Implementation Guide](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Fintelamtpowerstatetransitions.htm )

**Comment by mtpham-1** [comment]
Hi Madhavi,

In a KVM or SOL session, power off or reset is achievable and a must for AMT power operations. From my note above, you can do resets and power off when choosing from this dropdown list from the 3 dots. We need to do the same action from those icons I circled. If we need to meet to discuss let me know.
