### ISSUE TITLE
UI always shows "Certificate Not Yet Uploaded"

### ISSUE THREAD

**Issue by lobando** [open-amt-cloud-toolkit/sample-web-ui#483]
On the Domains page, the UI always shows Certificate Not Yet Uploaded even if the certificate is there

**Comment by rsdmike** [comment]
Can you tell us what browser and version you are using, what OS and what version as well and we'll see if we can reproduce. We typically do our testing in a chromium based browser (IE Edge, Chrome, Brave).

**Comment by lobando** [comment]
> Can you tell us what browser and version you are using, what OS and what version as well and we'll see if we can reproduce. We typically do our testing in a chromium based browser (IE Edge, Chrome, Brave).

I'm using Chrome - Official Build for this, also I'm using a deployment with Kubernetes on the cloud.

**Comment by rsdmike** [comment]
Hey @lobando, are you talking about when you go to edit? It is merely there to show if you've chosen a file and its ready to be saved. Otherwise -- since its a secret, we never return back to the UI to indicate one has _previously_ been uploaded. We could consider adding a flag to the payload when retrieving and updating the UI , however that could be also confusing since I haven't uploaded a new certificate to be uploaded the server. So I think we'd have to consider it a little differently. I'm gonna mark this as an enhancement for now.
