### ISSUE TITLE
Going to login page while logged in does not redirect to the dashboard

### ISSUE THREAD

**Issue by Craig-Spencer-12** [open-amt-cloud-toolkit/sample-web-ui#56]
when visiting http://localhost:4200/login (or wherever the web-ui is hosted) while already logged in, the ui presents the login page with a functional navigation bar to the side. I'm guessing that this is unintended as the user should either have access or be presented with the login page but not both.

A simple redirect from the login page to the dashboard when the user is logged in should fix this issue.

I found this because I saved a bookmark for the login page and went there while already logged in

![login-bug](https://user-images.githubusercontent.com/65725233/109405592-5025a400-792f-11eb-9821-7f86888ac4c9.png)

**Comment by rsdmike** [comment]
I see a few options
1) log out the user since they navigated to the /login route -- which indicates that they would want to log in under a different account
2) redirect as you suggest
3) leave the user logged in (it knows you are logged in since the navbar is there) but simply hide the navbar since the login route was navigated to

**Comment by matt-primrose** [comment]
@rsdmike  provided an answer and no additional activity.  Closing issue as resolved.
